"use client";

import { Skeleton } from "@/components/ui/skeleton";
import { useReferenceImages } from "@/hooks/useInvoices";

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

export default function ReferenceImageTab({ stem }: { stem: string }) {
  const { images, isLoading, error } = useReferenceImages(stem);

  if (isLoading) return <Skeleton className="h-64 bg-white/[0.05] rounded-lg" />;
  if (error) return <p className="text-red-400 text-sm">Failed to check reference images.</p>;
  if (images.length === 0) {
    return (
      <div className="bg-[#0d0d0d] border border-white/[0.07] rounded-lg p-8 text-center">
        <p className="text-zinc-500 text-sm">No reference images available.</p>
        <p className="text-zinc-600 text-xs mt-1">Reference images are generated by PaddleOCR only.</p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {images.map((img) => (
        <div key={img} className="bg-[#0d0d0d] border border-white/[0.07] rounded-lg overflow-hidden">
          <p className="text-xs text-zinc-500 font-mono px-3 py-2 border-b border-white/[0.06]">{img}</p>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={`${API_BASE}/reference/${img}`}
            alt={img}
            className="w-full object-contain max-h-[70vh]"
          />
        </div>
      ))}
    </div>
  );
}
